language: d

# start most recent dmd and ldc first, then older versions. (don't bother with pre-release')
# For available compilers see: https://semitwist.com/travis-d-compilers
d:
  - ldc
  - dmd
  - dmd-2.087.0
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - ldc-1.17.0 # eq to dmd v2.087
  - ldc-1.16.0 # eq to dmd v2.086.1
  - ldc-1.15.0 # eq to dmd v2.085.1
  - ldc-1.14.0 # eq to dmd v2.084.1
  - ldc-1.13.0 # eq to dmd v2.083.1
  - ldc-1.12.0 # eq to dmd v2.082.1

script:
  - dub build --config=full --compiler=${DC}
  - dub run --config=test --compiler=${DC}
  - cd example && dub build --compiler=${DC} && ./ddbctest --connection=sqlite:ddbc-test.sqlite

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - libsqlite3-dev
      - gcc-6
  homebrew:
    brewfile: true

# GDC versions need to be setup with correct version of gcc
# The integration tests can only run in Linux container
matrix:
  include:
    - env: NAME="MySQL Integration Test with DUB upgrade"
      d: dmd
      os: linux
      services:
        - mysql
      before_script: mysql --user=travis -e 'CREATE DATABASE ddbctest;'
      script:
        - dub upgrade
        - dub build --config=full
        - cd example && dub build && ./ddbctest --connection=mysql:127.0.0.1 --database=ddbctest --user=travis
    - env: NAME="MySQL Integration Test"
      d: dmd
      os: linux
      services:
        - mysql
      before_script: mysql --user=travis -e 'CREATE DATABASE ddbctest;'
      script:
        - dub build --config=full
        - cd example && dub build && ./ddbctest --connection=mysql:127.0.0.1 --database=ddbctest --user=travis
    - env: NAME="PostgreSQL Integration Test"
      d: dmd
      os: linux
      services:
        - postgresql
      before_script: psql -c 'create database ddbctest;' -U postgres
      script:
        - dub build --config=full
        - cd example && dub build && ./ddbctest --connection=pgsql:127.0.0.1 --database=ddbctest --user=postgres
    - d: dmd
      os: osx
    - d: ldc
      os: osx
    - d: dmd-beta
    - d: gdc
  allow_failures:
    - d: dmd-beta
    - d: gdc
