language: d

sudo: required
dist: trusty

# start most recent dmd and ldc first, then pre-release & older versions
d:
  - dmd
  - ldc
  - dmd-2.071.2
  - dmd-2.070.0
  - dmd-2.069.2
  - ldc-1.1.0-beta3
  - ldc-0.17.2
  - gdc

# make sure our Mac build uses OS X 10.11 rather than default (10.9) so we have more recent sqlite
osx_image: xcode7.3

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=full --compiler=${DC}
  - dub run --config=test --compiler=${DC}
  - cd example && dub build --compiler=${DC} && ./ddbctest --connection=sqlite:ddbc-test.sqlite

addons:
  apt:
    packages: [ libsqlite3-dev ]

# GDC lags behind DMD.
matrix:
  allow_failures:
    - d: gdc
