language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - ldc
  - gdc

# make sure our Mac build uses OS X 10.11 rather than default (10.9) so we have more recent sqlite
osx_image: xcode7.3

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub test --config=SQLite
  - dub run -c test
  - cd example && dub build && ./ddbctest --connection=sqlite:ddbc-test.sqlite
  
# GDC lags behind DMD
matrix:
  allow_failures:
    - d: gdc
