language: d

# See: https://docs.travis-ci.com/user/trusty-ci-environment/#Routing-to-Trusty
sudo: required
dist: trusty

# start most recent dmd and ldc first, then older versions. (don't bother with pre-release')
d:
  - dmd
  - ldc
  - dmd-2.071.2
  - dmd-2.070.0
  - dmd-2.069.2
  - gdc-4.8.2

# make sure our Mac build uses latest OS X. See: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
osx_image: xcode8

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=full --compiler=${DC}
  - dub run --config=test --compiler=${DC}
  - cd example && dub build --compiler=${DC} && ./ddbctest --connection=sqlite:ddbc-test.sqlite

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsqlite3-dev
      - gcc-4.8

# GDC versions need to be setup with correct version of gcc
matrix:
  allow_failures:
    - d: gdc-4.8.2
    - os: osx
      d: ldc
